version: "3"

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.8
    environment:
      TZ: 'Italy/Rome'
      WEBPASSWORD: '' # security first!
      DNSSEC: 'true'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    ports:
      - $PRIVATE_IP:53:53/tcp
      - $PRIVATE_IP:53:53/udp
      - $PRIVATE_IP:67:67/udp
      - $PRIVATE_IP:80:80/tcp
    dns:
      - 1.1.1.1
      - 1.0.0.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard:1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SERVERURL=$PUBLIC_IP
      - SERVERPORT=443
      - PEERS=$VPN_PEERS
      - PEERDNS=$PRIVATE_IP #private ip (pihole is dns)
    # - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./wireguard/config:/config
      - ./wireguard/lib/modules:/lib/modules
    ports:
      - 443:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  dnscrypt:
    image: jedisct1/dnscrypt-server
    container_name: dnscrypt
    command: "init -A -N my.dsn.com -E '$PRIVATE_IP:5554' -M '0.0.0.0:9100'"
    volumes:
      - /etc/dnscrypt/keys:/opt/encrypted-dns/etc/keys
      - /lib/modules:/lib/modules
    ports:
      - $PRIVATE_IP:5554:5554/udp
      - $PRIVATE_IP:5554:5554/tcp
      - $PRIVATE_IP:9100:9100/tcp
    restart: unless-stopped
