name: Sync
on: [workflow_dispatch]
jobs:
  deploy:
    name: Sync docker-compose.yml
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.PUBLIC_IP }}
          if_key_exists: ignore
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PUBLIC_IP }} >> ~/.ssh/known_hosts
      - name: Sync docker-compose
        run: rsync docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.PUBLIC_IP }}:${{ secrets.REMOTE_PATH }}
      - name: Restart services
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.PUBLIC_IP }} 'PUBLIC_IP=${{ secrets.PUBLIC_IP }} PRIVATE_IP=${{ secrets.PRIVATE_IP }} docker-compose up --force-recreate -d'
